const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const dataPath = path.join(process.cwd(), "data", "keys.json");
const REDEEM_LOG_WEBHOOK_URL = "https://discord.com/api/webhooks/1534255329230065704/I_WByyZTcmnqjISjxKB61BwaInwokLNXpuTmIPqfufsJGotQhLtFyA1zUgtWh7sfND--";

function makeKey() {
  return crypto.randomBytes(9).toString("hex").toUpperCase();
}

async function postGenerateLog(discordUsername, key, minutes) {
  try {
    await fetch(REDEEM_LOG_WEBHOOK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        embeds: [
          {
            title: "🆕 Key Generated",
            color: 0x1fb8f0,
            fields: [
              { name: "🔑 Key", value: `\`${key}\``, inline: true },
              { name: "⏱️ Duration", value: `${minutes} minute(s)`, inline: true },
              { name: "👮 Generated By", value: discordUsername, inline: true }
            ],
            timestamp: new Date().toISOString()
          }
        ]
      })
    });
  } catch (error) {
    console.error("Could not post generate log:", error);
  }
}

module.exports = {
  ownerOnly: true,

  data: new SlashCommandBuilder()
    .setName("generatekey")
    .setDescription("Generates a timed key")
    .addIntegerOption(option =>
      option
        .setName("minutes")
        .setDescription("How long the key lasts after redemption")
        .setRequired(true)
        .setMinValue(1)
    ),

  async execute(interaction) {
    const minutes = interaction.options.getInteger("minutes");
    const key = makeKey();

    const database = JSON.parse(
      fs.readFileSync(dataPath, "utf8")
    );

    database.keys.push({
      key,
      minutes,
      createdAt: Date.now(),

      redeemed: false,
      redeemedAt: null,
      redeemedBy: null,
      expiresAt: null,

      paused: false,
      pausedAt: null,
      remainingMs: null,

      revoked: false,
      revokedAt: null
    });

      console.log("Saving new key to:", dataPath);
      console.log("New key:", key);

    fs.writeFileSync(
      dataPath,
      JSON.stringify(database, null, 2)
    );

    postGenerateLog(interaction.user.tag, key, minutes);

    const embed = new EmbedBuilder()
      .setTitle("✅   Key Generated")
      .addFields(
        { name: "Key", value: `\`${key}\`` },
        {
          name: "Duration",
          value: `${minutes} minute(s) after redemption`
        },
        {
          name: "Status",
          value: "Unused — timer has not started"
        }
      )
      .setTimestamp();

    await interaction.reply({
  embeds: [embed]
});
  }
};